### ISSUE TITLE
Use google authentication with django social auth.

### ISSUE THREAD

**Issue by nermolov** [lociii/jukebox#48]
Is it possible to login with google using django social auth? It says it is supported.

**Comment by lociii** [comment]
Sure. Try to add the Google backend to AUTHENTICATION_BACKENDS and SOCIAL_AUTH_ENABLED_BACKENDS in your config.
You should add an image for Google as well or override the login.html template.

**Comment by nermolov** [comment]
Where exactly is this config going to be located and what do I add?

**Comment by lociii** [comment]
When installing from pip the configuration will be found in the home directory of the user running the jukebox.
e.g. /home/johndoe/.jukebox/settings_local.py
