### ISSUE TITLE
Newbe Guide

### ISSUE THREAD

**Issue by Doedelpumpe** [lociii/jukebox#50]
Is there any chance to get a How-To in detail ?
I was fighting through those steps in the project-description but at the end it does not work.
I am using a RPi 3 Model B.
I would gladly build it to a jukebox with a WLan Access Point for a jukebox with a voting system via a website reachable over something like "juke.box" as URL.
I made my RPi to a Access Point already. But can not get a jukebox to run yet. A Video from a fresh RPi to working jukebox would be the most awesome thing but a more detailed text-Guide (from zero to jukebox) should work as well :)
Thanks already :)

**Comment by lociii** [comment]
Unfortunately the project hasn't been worked on for a few years now and is already marked as unmaintained.
Sorry.
